name: Update

on:
  watch:
    types: [started]
  schedule:
    - cron: 0,30 * * * *

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 3

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"

    - name: Update
      run: |
        # 国内IPV6-TV源
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O IPTV-V6.m3u
       
        
       
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CCTV-V6.m3u && sed -i -n '/央视频道/,+1p'  CCTV-V6.m3u 
        sed -i '1i #EXTM3U' CCTV-V6.m3u
        sed -i '/^\s*$/d' CCTV-V6.m3u

        rm -f CNTV-V6.m3u && touch CNTV-V6.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV1.m3u && sed -i -n '/卫视频道/,+1p' CNTV1.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV2.m3u && sed -i -n '/NewTV系列/,+1p' CNTV2.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV3.m3u && sed -i -n '/超清频道/,+1p' CNTV3.m3u

        cat CCTV-V6.m3u >> CNTV-V6.m3u
        cat CNTV1.m3u >> CNTV-V6.m3u
        cat CNTV2.m3u >> CNTV-V6.m3u
        cat CNTV3.m3u >> CNTV-V6.m3u
        rm -f CNTV1.m3u CNTV2.m3u CNTV3.m3u
        sed -i '/#EXTM3U/d' CNTV-V6.m3u
        sed -i '1i #EXTM3U' CNTV-V6.m3u
        sed -i '/^\s*$/d' CNTV-V6.m3u

        # 国内IPV4-TV源
        wget https://raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv4.m3u  -O IPTV-V4.m3u
        
        wget https://raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv4.m3u  -O CCTV-V4.m3u && sed -i -n '/央视频道/,+1p'  CCTV-V4.m3u 
        sed -i '1i #EXTM3U' CCTV-V4.m3u
        sed -i '/^\s*$/d' CCTV-V4.m3u

        rm -f CNTV-V4.m3u && touch CNTV-V4.m3u
        wget https://raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv4.m3u -O CNTV1.m3u && sed -i -n '/卫视频道/,+1p' CNTV1.m3u
        wget https://raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv4.m3u  -O CNTV2.m3u && sed -i -n '/NewTV系列/,+1p' CNTV2.m3u
        wget https://raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv4.m3u  -O CNTV3.m3u && sed -i -n '/超清频道/,+1p' CNTV3.m3u

        cat CCTV-V4.m3u >> CNTV-V4.m3u
        cat CNTV1.m3u >> CNTV-V4.m3u
        cat CNTV2.m3u >> CNTV-V4.m3u
        cat CNTV3.m3u >> CNTV-V4.m3u
        rm -f CNTV1.m3u CNTV2.m3u CNTV3.m3u
        sed -i '/#EXTM3U/d' CNTV-V4.m3u
        sed -i '1i #EXTM3U' CNTV-V4.m3u
        sed -i '/^\s*$/d' CNTV-V4.m3u

        

        # 成人源
        # rm -f Adult.m3u && wget http://adultiptv.net/chs.m3u -O Adult.m3u
        # sed -i 's/XXX/成人频道/' Adult.m3u
        # sed -i 's/AdultIPTV.net //g' Adult.m3u
        # wget https://yang-1989.eu.org/m3u/Adult -O AdultVideo.txt
        # # sed -i -n '/日本/,+1p' AdultVideo.txt
        # # sed -i 's/日本/成人视频/' AdultVideo.txt
        # echo '' >> Adult.m3u && cat AdultVideo.txt >> Adult.m3u
        # rm -f AdultVideo.txt
        # sed -i '/#EXTM3U/d' Adult.m3u
        # sed -i '1i #EXTM3U' Adult.m3u
        # sed -i '/^\s*$/d' Adult.m3u


        # 直播源
        rm -f Live.m3u && wget https://bit.ly/IPTV-Gather -O Live.m3u
        # sed -i 's/XXX/成人频道/' Adult.m3u
        # sed -i 's/AdultIPTV.net //g' Adult.m3u
        # wget https://yang-1989.eu.org/m3u/Adult -O AdultVideo.txt
        # # sed -i -n '/日本/,+1p' AdultVideo.txt
        # # sed -i 's/日本/成人视频/' AdultVideo.txt
        # echo '' >> Adult.m3u && cat AdultVideo.txt >> Adult.m3u
        # rm -f AdultVideo.txt
        sed -i '/#EXTM3U/d' Live.m3u
        sed -i '1i #EXTM3U' Live.m3u
        sed -i '/^\s*$/d' Live.m3u

        # 全网源
        rm -f Gather.m3u && wget --header="User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" https://live.iptv365.org/live.m3u -O Gather.m3u
        # sed -i 's/XXX/成人频道/' Adult.m3u
        # sed -i 's/AdultIPTV.net //g' Adult.m3u
        # wget https://yang-1989.eu.org/m3u/Adult -O AdultVideo.txt
        # # sed -i -n '/日本/,+1p' AdultVideo.txt
        # # sed -i 's/日本/成人视频/' AdultVideo.txt
        # echo '' >> Adult.m3u && cat AdultVideo.txt >> Adult.m3u
        # rm -f AdultVideo.txt
        sed -i '/#EXTM3U/d' Gather.m3u
        sed -i '1i #EXTM3U' Gather.m3u
        sed -i '/^\s*$/d' Gather.m3u



        
        # 节目源
        rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
        echo "Auto Update in ${{ steps.date.outputs.date }}

        ## Star History
        <a href='https://star-history.com/#peterHchina/iptv&Date'>
        <picture>
        <source media='(prefers-color-scheme: dark)' srcset='https://api.star-history.com/svg?repos=peterHchina/iptv&type=Date&theme=dark' />
        <source media='(prefers-color-scheme: light)' srcset='https://api.star-history.com/svg?repos=peterHchina/iptv&type=Date' />
        <img alt='Star History Chart' src='https://api.star-history.com/svg?repos=peterHchina/iptv&type=Date' />
        </picture>
        </a>" > README.md

    - name: Clean
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git checkout --orphan latest_branch
        git add -A
        git commit -am "${{ steps.date.outputs.date }}"
        git branch -D main
        git branch -m main
    - name: Push
      run: git push -f origin main
